# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20d99183352b8d5f18e76b98f701c79bf65b3b274c9c40591c7b05f4f1d7e27b35fa82fd62c07cdcde288909c55f88efc3156e679603913b5215d50822d3d132

test:
  secret_key_base: 306797d90d5247785358451f22a5b4f011d28ec3f34d7a9fb4659cd60241c9f3dab025b9a4ec31f4dff551d4d1e9aa4c1f6e820c796b084c3f1210033f98172e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
